from shared.constants import (
    STATE_CLAIM_INITIALIZE,
    STATE_START_REGISTRATION_QUEUE,
    STATE_ELIGIBILITY_VERIFICATION_QUEUE,
    STATE_VERIFY_REGISTRATION_INFO_QUEUE,
    STATE_SELF_REGISTRATION_QUEUE,
    STATE_HOSPITAL_FACESHEET_FAX_QUEUE,
    STATE_HOSPITAL_FACESHEET_DOWNLOAD_QUEUE,
    STATE_CLINIC_INSURANCE_IMAGE_DOWNLOAD_QUEUE,
    STATE_FIX_ELIGIBILITY_ERROR_QUEUE,
    STATE_MANUAL_ELIGIBILITY_VERIFICATION_QUEUE,
    STATE_PATIENT_DEDUPLICATION_QUEUE,
    STATE_FACESHEET_NOT_RECEIVED_COORDINATOR_QUEUE,
    STATE_SELF_REGISTRATION_NOT_RECEIVED_COORDINATOR_QUEUE,
    STATE_CASE_CLOSED_SELF_PAY,
    STATE_CASE_READY_FOR_CLAIM_CREATION,
    STATE_CASE_CLOSED_DUPLICATE,
    HANDLER_INITIALIZE,
    HANDLER_GATHER_REGISTRATION,
    HANDLER_VERIFY_REGISTRATION,
    HANDLER_VERIFY_ELIGIBILITY,
    HANDLER_SELF_REGISTRATION,
    HANDLER_HOSPITAL_FACESHEET_REQUEST,
    HANDLER_NORMALIZE_CASE,
    HANDLER_CLOSE_OUT,
    TERMINAL_STATES,
)

# ── Demographics workflow entry states ────────────────────────
# These are the states that trigger the Initialize handler
DEMOGRAPHICS_ENTRY_STATES = {
    "DEMOGRAPHICS_CREATED",       # ──► Our seeded state ✅
    "CLAIM_INITIALIZE",           # ──► Standard entry state
    STATE_CLAIM_INITIALIZE,       # ──► From constants
}

# Maps case state_code → handler key
STATE_TO_HANDLER: dict[str, str] = {

    # ── Initialize Demographics Flow ──────────────────────────
    STATE_CLAIM_INITIALIZE          : HANDLER_INITIALIZE,
    "DEMOGRAPHICS_CREATED"          : HANDLER_INITIALIZE,   

    # ── Registration Flow ─────────────────────────────────────
    STATE_START_REGISTRATION_QUEUE  : HANDLER_GATHER_REGISTRATION,

    # ── Verify Registration ───────────────────────────────────
    STATE_VERIFY_REGISTRATION_INFO_QUEUE: HANDLER_VERIFY_REGISTRATION,

    # ── Eligibility Verification ──────────────────────────────
    STATE_ELIGIBILITY_VERIFICATION_QUEUE: HANDLER_VERIFY_ELIGIBILITY,

    # ── Self Registration ─────────────────────────────────────
    STATE_SELF_REGISTRATION_QUEUE   : HANDLER_SELF_REGISTRATION,

    # ── Hospital Facesheet ────────────────────────────────────
    STATE_HOSPITAL_FACESHEET_FAX_QUEUE     : HANDLER_HOSPITAL_FACESHEET_REQUEST,
    STATE_HOSPITAL_FACESHEET_DOWNLOAD_QUEUE: HANDLER_HOSPITAL_FACESHEET_REQUEST,

    # ── Human Queue States → Normalize ───────────────────────
    STATE_CLINIC_INSURANCE_IMAGE_DOWNLOAD_QUEUE          : HANDLER_NORMALIZE_CASE,
    STATE_FIX_ELIGIBILITY_ERROR_QUEUE                    : HANDLER_NORMALIZE_CASE,
    STATE_MANUAL_ELIGIBILITY_VERIFICATION_QUEUE          : HANDLER_NORMALIZE_CASE,
    STATE_PATIENT_DEDUPLICATION_QUEUE                    : HANDLER_NORMALIZE_CASE,
    STATE_FACESHEET_NOT_RECEIVED_COORDINATOR_QUEUE       : HANDLER_NORMALIZE_CASE,
    STATE_SELF_REGISTRATION_NOT_RECEIVED_COORDINATOR_QUEUE: HANDLER_NORMALIZE_CASE,

    # ── Terminal States ───────────────────────────────────────
    STATE_CASE_CLOSED_DUPLICATE     : HANDLER_CLOSE_OUT,
}


def resolve_handler(case_state: str) -> str:
    """
    Resolve handler key from case state_code.
    Explicit mapping always wins.
    Falls back to NORMALIZE for unknown states.
    """
    if case_state in STATE_TO_HANDLER:
        return STATE_TO_HANDLER[case_state]

    if case_state in TERMINAL_STATES:
        return HANDLER_NORMALIZE_CASE

    return HANDLER_NORMALIZE_CASE