# ── Case / workflow identity ────────────────────────────────────────────────
CASE_TYPE_DEMOGRAPHICS = "DEMOGRAPHICS"
WORKFLOW_NAME_DEMOGRAPHICS = "DEMOGRAPHICS_WORKFLOW"
WORKFLOW_VERSION_V1 = "v1"

# ── RCM_CASE state_code values ───────────────────────────────────────────────
STATE_CLAIM_INITIALIZE = "CLAIM_INITIALIZE"
STATE_START_REGISTRATION_QUEUE = "START_REGISTRATION_QUEUE"
STATE_ELIGIBILITY_VERIFICATION_QUEUE = "ELIGIBILITY_VERIFICATION_QUEUE"
STATE_CLAIM_CREATION_QUEUE = "CLAIM_CREATION_QUEUE"
STATE_FIX_ELIGIBILITY_ERROR_QUEUE = "FIX_ELIGIBILITY_ERROR_QUEUE"
STATE_MANUAL_ELIGIBILITY_VERIFICATION_QUEUE = "MANUAL_ELIGIBILITY_VERIFICATION_QUEUE"
STATE_PATIENT_DEDUPLICATION_QUEUE = "PATIENT_DEDUPLICATION_QUEUE"
STATE_VERIFY_REGISTRATION_INFO_QUEUE = "VERIFY_REGISTRATION_INFO_QUEUE"
STATE_SELF_REGISTRATION_QUEUE = "SELF_REGISTRATION_QUEUE"
STATE_SELF_REGISTRATION_NOT_RECEIVED_COORDINATOR_QUEUE = (
    "SELF_REGISTRATION_NOT_RECEIVED_COORDINATOR_QUEUE"
)
STATE_HOSPITAL_FACESHEET_DOWNLOAD_QUEUE = "HOSPITAL_FACESHEET_DOWNLOAD_QUEUE"
STATE_HOSPITAL_FACESHEET_FAX_QUEUE = "HOSPITAL_FACESHEET_FAX_QUEUE"
STATE_FACESHEET_NOT_RECEIVED_COORDINATOR_QUEUE = (
    "FACESHEET_NOT_RECEIVED_COORDINATOR_QUEUE"
)
STATE_CLINIC_INSURANCE_IMAGE_DOWNLOAD_QUEUE = "CLINIC_INSURANCE_IMAGE_DOWNLOAD_QUEUE"
STATE_CASE_CLOSED_SELF_PAY = "CASE_CLOSED_SELF_PAY"
STATE_CASE_READY_FOR_CLAIM_CREATION = "CASE_READY_FOR_CLAIM_CREATION"
STATE_CASE_CLOSED_DUPLICATE = "CASE_CLOSED_DUPLICATE"

TERMINAL_STATES = frozenset(
    {STATE_CASE_CLOSED_SELF_PAY, STATE_CASE_READY_FOR_CLAIM_CREATION, STATE_CASE_CLOSED_DUPLICATE}
)

# ── RCM_CASE substate_code values ────────────────────────────────────────────
SUBSTATE_WAITING_ON_PATIENT = "WAITING_ON_PATIENT"
SUBSTATE_WAITING_ON_HOSPITAL = "WAITING_ON_HOSPITAL"
SUBSTATE_WAITING_ON_CLINIC = "WAITING_ON_CLINIC"
SUBSTATE_WAITING_ON_HUMAN_REVIEW = "WAITING_ON_HUMAN_REVIEW"
SUBSTATE_WAITING_ON_MANUAL_ELIGIBILITY = "WAITING_ON_MANUAL_ELIGIBILITY"
SUBSTATE_WAITING_ON_DUPLICATE_RESOLUTION = "WAITING_ON_DUPLICATE_RESOLUTION"
SUBSTATE_AUTO_VERIFICATION_IN_PROGRESS = "AUTO_VERIFICATION_IN_PROGRESS"
SUBSTATE_OCR_EXTRACTION_COMPLETE = "OCR_EXTRACTION_COMPLETE"
SUBSTATE_POLICY_CONFLICT_DETECTED = "POLICY_CONFLICT_DETECTED"
SUBSTATE_IMAGE_MISMATCH = "IMAGE_MISMATCH"
SUBSTATE_BAD_REGISTRATION_DATA = "BAD_REGISTRATION_DATA"

# ── RCM_TASK state_code values ───────────────────────────────────────────────
TASK_OPEN = "OPEN"
TASK_IN_PROGRESS = "IN_PROGRESS"
TASK_WAITING = "WAITING"
TASK_DONE = "DONE"
TASK_CANCELED = "CANCELED"
TASK_SUPERSEDED = "SUPERSEDED"

TASK_CLOSE_REASON_COMPLETED = "COMPLETED"
TASK_CLOSE_REASON_CANCELED = "CANCELED"
TASK_CLOSE_REASON_SUPERSEDED = "SUPERSEDED"
TASK_CLOSE_REASON_ESCALATED = "ESCALATED"

# ── Handler keys ─────────────────────────────────────────────────────────────
HANDLER_INITIALIZE = "DEMO_INITIALIZE"
HANDLER_GATHER_REGISTRATION = "DEMO_GATHER_REGISTRATION"
HANDLER_VERIFY_REGISTRATION = "DEMO_VERIFY_REGISTRATION"
HANDLER_VERIFY_ELIGIBILITY = "DEMO_VERIFY_ELIGIBILITY"
HANDLER_SELF_REGISTRATION = "DEMO_SELF_REGISTRATION"
HANDLER_HOSPITAL_FACESHEET_REQUEST = "DEMO_HOSPITAL_FACESHEET_REQUEST"
HANDLER_NORMALIZE_CASE = "DEMO_NORMALIZE_CASE"
HANDLER_CLOSE_OUT = "DEMO_CLOSE_OUT"

# ── Fact scopes ───────────────────────────────────────────────────────────────
FACT_SCOPE_DEMOGRAPHICS = "DEMOGRAPHICS"
FACT_SCOPE_ELIGIBILITY = "ELIGIBILITY"
FACT_SCOPE_DOCUMENT = "DOCUMENT"
FACT_SCOPE_OUTREACH = "OUTREACH"
FACT_SCOPE_DUPLICATE = "DUPLICATE"

# ── Document types ────────────────────────────────────────────────────────────
DOC_TYPE_INSURANCE_CARD = "INSURANCE_CARD"
DOC_TYPE_FACESHEET = "FACESHEET"
DOC_TYPE_PRIOR_AUTH = "PRIOR_AUTH"

DOC_SOURCE_FAX = "FAX"
DOC_SOURCE_EMR = "EMR"
DOC_SOURCE_UPLOAD = "UPLOAD"
DOC_SOURCE_PATIENT_PORTAL = "PATIENT_PORTAL"

# ── Insurance types that require manual eligibility (no electronic path) ─────
MANUAL_ELIGIBILITY_INSURANCE_TYPES = frozenset(
    {"workers compensation", "auto", "personal injury", "9"}
)

# ── Billing method sentinel for self-pay ─────────────────────────────────────
BILLING_METHOD_SELF_PAY = 0

# ── Clearinghouse identifiers ─────────────────────────────────────────────────
CLEARINGHOUSE_AVAILITY = "AVAILITY"

# ── Claim intake: STATUS values considered "new" in allofactorv3 ─────────────
# STATUS=1 → new/pending, adjust per tenant convention
CLAIM_STATUS_NEW = 1

# ── Event types ───────────────────────────────────────────────────────────────
EVENT_DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
EVENT_TASK_COMPLETED = "TASK_COMPLETED"
EVENT_HUMAN_REVIEW_COMPLETED = "HUMAN_REVIEW_COMPLETED"
EVENT_PATIENT_SELF_REGISTRATION_COMPLETED = "PATIENT_SELF_REGISTRATION_COMPLETED"
EVENT_MANUAL_OVERRIDE = "MANUAL_OVERRIDE"
